ports:
  - port: 8080
    onOpen: open-browser
    visibility: public
tasks:
  - name: Install http-server
    init: npm install -g http-server
  - name: Start http server
    command: npx http-server